[tool.poetry]
name = "leadanne2"
version = "0.1.0"
description = ""
authors = ["Pedro Antonio <pedro@z33dd.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2.6"

[tool.poetry.group.dev.dependencies]
black = "^23.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
