name: Deploy master
on:
  push:
    branches:
    - main

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set Dockerfile for env
      run: mv ./Dockerfile.server Dockerfile

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy server to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Leadann2-server2
        environment_name: Leadann2-server2-env
        version_label: ${{ github.sha }}
        region: sa-east-1
        deployment_package: deploy.zip

    - name: Deploy worker to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Leadanne2-worker
        environment_name: Leadanne2-worker-env
        version_label: ${{ github.sha }}
        region: sa-east-1
        deployment_package: deploy.zip

  build-worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set Dockerfile for env
      run: mv ./Dockerfile.worker Dockerfile
      
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy server to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Leadann2-worker
        environment_name: Leadann2-worker-env
        version_label: ${{ github.sha }}
        region: sa-east-1
        deployment_package: deploy.zip

    - name: Deploy worker to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Leadanne2-worker
        environment_name: Leadanne2-worker-env
        version_label: ${{ github.sha }}
        region: sa-east-1
        deployment_package: deploy.zip
